# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test"
  lane :tests do
    xcode_select("/Applications/Xcode.app")

    run_tests(project: "CI_CD_Practice.xcodeproj",
	      scheme: "CI_CD_Practice",
	      device: "iPhone 13",
	      clean: true)
  end
end
